version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ngx-rrhh-app
    volumes:
      - ../:/workspace
      - /workspace/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:3001/api
    command: npm start
    networks:
      - devnet

networks:
  devnet:
    external: false
